name: test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: asdf-vm v2
        uses: asdf-vm/actions/install@v2
      - name: Poetry export
        run: poetry export --with dev --format requirements.txt --output ./requirements.txt
      - name: Install Python packages
        run: pip install -r requirements.txt
      - name: Run test
        run: invoke test
